function(custom_setup_step)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(IBus REQUIRED ibus-1.0)

    if(IBus_FOUND)
        include_directories(${IBus_INCLUDE_DIRS})
        link_directories(${IBus_LIBRARY_DIRS})
    endif(IBus_FOUND)
endfunction()

function(custom_compile_step)
    if (NOT WIN32)
        target_link_libraries(${APP_LIB_TARGET} ${IBus_LIBRARIES})
    endif()
endfunction()
