name: CI

env:
  BUILD_CONFIGURATION: Release
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          clean: false
          fetch-depth: 0
      - name: Get Dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get install x11-xserver-utils libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev gcc make g++ libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libvulkan1 mesa-vulkan-drivers vulkan-tools libvulkan-dev libasound2-dev libflac-dev libogg-dev libtool libvorbis-dev libopus-dev libsndfile1-dev libglew-dev libssl-dev zlib1g zlib1g-dev ibus libibus-1.0-dev libglfw3 libglfw3-dev libyaml-cpp-dev libxkbcommon-dev
      - name: Checkout Submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install
        shell: bash
        run: ./ci.sh
