on:
  push:
    tags:
      - 'v*'
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Create archive
        shell: bash
        run: |
          rm -rf .git/
          cd hanzi_lookup || exit
          cargo vendor || (ls hanzi_lookup && exit)
          cd .. || exit
          tar cfJ untitled-ibus-handwriting.tar.xz . || echo "Might have failed"
      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          body: |
            Check our discord for patch notes: https://discord.gg/4kyWu2Vu
            More on what is done this month can be found on the latest newsletter entry: https://madladsquad.com/#monthly-newsletter
          draft: false
          prerelease: false
          files: untitled-ibus-handwriting.tar.xz
          generate_release_notes: false
